console.log('________________________LINKS_________________________')
const Usuario = require('./Usuario')
const Vendedor = require('./Vendedor')
const Cliente = require('./Cliente')
const Categoria = require('./Categoria')
const Productos = require('./Productos')
const Carrito = require('./Carrito')
const Compra = require('./Compra')
const Envios = require('./Envios')
const Factura = require('./Factura')
console.log('________________________USUARIO_________________________')
let usuario1 = new Usuario(1032796840, 'Johan', '123')
let usuario2 = new Usuario(2102369854, 'Lorena', 'lk4445')
let usuario3 = new Usuario(1111023654, 'Pedro', 'srfasf01')
let usuario4 = new Usuario(8023654412, 'Alonso', 'asgfsdgh')
console.log(usuario1, usuario2, usuario3, usuario4)
    //console.log(usuario1, usuario2, usuario3, usuario4)
console.log('________________________CLIENTE_________________________')
let cliente1 = new Cliente(2102369854, 'Lorena', 'lk4445')
let cliente2 = new Cliente(8023654412, 'Alonso', 'asgfsdgh')
    //------------
cliente1.agregarcliente(usuario2)
cliente2.agregarcliente(usuario4)
console.log(cliente1)
console.log(cliente2)
console.log('________________________VENDEDOR_________________________')
let vendedor1 = new Vendedor(1032796840, 'Johan', '123')
let vendedor2 = new Vendedor(1111023654, 'Pedro', 'srfasf01')
    //------------
vendedor1.agregarvendedor(usuario1)
vendedor2.agregarvendedor(usuario3)
console.log(vendedor1)
console.log(vendedor2)
console.log('________________________CATEGORIA_________________________')
const categoria1 = new Categoria('Limpieza', 1, 14)
const categoria2 = new Categoria('Alimentos', 2, 10)
const categoria3 = new Categoria('Ropa', 3, 21)
console.log(categoria1, categoria2, categoria3)
console.log('________________________PRODUCTOS_________________________')
let producto1 = new Productos(12, 15000, 'Shampoo', categoria1, 20)
let producto2 = new Productos(59, 7500, 'Jabon de manos', categoria1, 40)
let producto3 = new Productos(34, 3000, 'Talcos', categoria1, 15)

let producto4 = new Productos(36, 20000, 'Pescado', categoria2, 9)
let producto5 = new Productos(59, 5890, 'Pasta', categoria2, 32)
let producto6 = new Productos(69, 29890, 'Aceite', categoria2, 15)

let producto7 = new Productos(74, 124990, 'Jean', categoria3, 90)
let producto8 = new Productos(36, 84990, 'Jogger', categoria3, 10)
let producto9 = new Productos(77, 159990, 'Chaqueta', categoria3, 7)

console.log(producto1, producto2, producto3, producto4, producto5, producto6, producto7, producto8, producto9)
console.log('________________________CARRITO_________________________')
let carrito1 = new Carrito(cliente1, 30, 1234)
carrito1.agregarproducto(producto1);
console.log(carrito1)
console.log('________________________COMPRA_________________________')
let compra1 = new Compra(carrito1)
console.log(compra1)
    //console.log(compra1.productos())
console.log('________________________ENVIOS_________________________')
console.log('________________________FACTURA_________________________')